// Auto-generated gear talents from Teriyaki — append to TALENT_MATH
  "Perfect Obliterate":{wd:15,conditional:true,note:"Critical hits increase weapon damage by 1% for 5s, stacking up to 25%."},
  "Perfect Intimidate":{wd:35,conditional:true,note:"+35% weapon damage to enemies within 10m while you have bonus armor."},
  "Perfect Focus":{wd:25,conditional:true,note:"Increases total weapon damage by 5% every second while aiming with 8x scope or higher, up to 50%."},
  "Perfect Headhunter":{hsd:15,conditional:true,note:"After killing an enemy with a headshot, your next weapon hit within 30s deals 125% of that killing blow's damage in addition to it."},
  "Perfect Overwatch":{wd:12,conditional:true,note:"After staying in cover for 10s, increase your and all allies' total weapon and skill damage by 12% as long as you remain in cover."},
  "Perfect Trauma":{wd:0,conditional:true,note:"Applies blind to an enemy hit in the head. Applies bleed to an enemy hit in the chest. Cooldown: 30s."},
  "Perfect Mad Bomber":{wd:0,conditional:true,note:"Grenade radius increased by 50%. Grenades that kill an enemy are refunded. Grenades can be cooked."},
  "Perfect Braced":{conditional:true,note:"While in cover weapon handling is increased by 45%."},
  "Perfect Skilled":{wd:0,conditional:true,note:"Skill kills have a 25% chance to reset skill cooldowns."},
  "Perfect Tag Team":{wd:0,conditional:true,note:"The last enemy damaged with a skill is marked. Dealing weapon damage to that enemy reduces active cooldowns by 6s. Cooldown: 4s."},
  "Perfect Tamper Proof":{wd:0,conditional:true,note:"Enemies that walk within 3m of your hive, turret, remote pulse, or decoy are shocked. Cooldown per skill: 10s."},
  "Perfect Reassigned":{wd:0,conditional:true,note:"Killing an enemy adds 1 round of random special ammo into your sidearm. Cooldown: 15s."},
  "Perfect Efficient":{wd:0,conditional:true,note:"Using an armor kit has a 50% chance to not consume the armor kit. Specialization armor kit bonuses are increased by 100%."},
  "Perfect Spark":{conditional:true,note:"Applying a status effect grants +15% weapon damage for 15s."},
  "Perfect Empathic Resolve":{wd:10,conditional:true,note:"Repairing an ally increases their weapon and skill damage by up to 15% for 20s."},
  "Perfect Kinetic Momentum":{wd:15,conditional:true,note:"Each active skill generates stacks granting +1% skill damage and +2% skill repair, up to 15 stacks."},
  "Perfect Vanguard":{wd:0,conditional:true,note:"Deploying a shield makes it invulnerable for 5s and grants 45% armor as bonus armor to allies for 20s."},
  "Perfect Spotter":{wd:15,conditional:true,note:"+15% weapon and skill damage to pulsed enemies."},
  "Perfect Glass Cannon":{wd:25,conditional:true,note:"All damage amplified by 25%. All damage taken amplified by 50%."},
  "Perfect Unbreakable":{conditional:true,note:"When armor is depleted, repair 95% of total armor. Cooldown 60s."},
  "Perfect Gunslinger":{wd:23,conditional:true,note:"Weapon swapping increases total weapon damage by 23% for 5s. This buff is lost for 5s if you weapon swap while it is active."},
  "Perfect Vigilance":{wd:25,conditional:true,note:"Increases weapon damage by 25%. Taking damage disables this bonus for 4s."},
  "Perfect Combined Arms":{conditional:true,note:"Shooting an enemy increases total skill damage by 25% for 3s."},
  "Perfect Tech Support":{conditional:true,note:"Skill kills increase total skill damage by 25% for 25s."},
  "Perfect Opportunistic":{wd:10,conditional:true,note:"Enemies hit with shotguns and marksman rifles amplify the damage they take by 10% from all sources for 5s."},
  "Perfect Safeguard":{conditional:true,note:"While at full armor, increases total skill repair by 130%."},
  "Perfect Leadership":{wd:0,conditional:true,note:"Performing a cover to cover grants 15% of your armor as bonus armor to you and all allies for 10s."},
  "Perfect Protector":{wd:0,conditional:true,note:"When your shield is damaged, you gain +5% and all other allies gain +15% of your armor as bonus armor for 3s. Cooldown: 3s."},
  "Perfect Adrenaline Rush":{wd:0,conditional:true,note:"When you are within 10m of an enemy, gain 20% bonus armor for 5s. Stacks up to 3 times. Cooldown: 5s."},
  "Perfect Galvanize":{wd:0,conditional:true,note:"Applying a Blind, Ensnare, Confuse, or Shock to an enemy grants 40% of your armor as bonus armor to you and all allies within 20m for 10s."},
  "Perfect Energize":{conditional:true,note:"Using an armor kit grants +1 skill tier for 15s. If already at skill tier 6, grants overcharge. Cooldown: 60s."},
  "Perfect Calculated":{wd:0,conditional:true,note:"Kills from cover reduce skill cooldowns by 10%."},
  "Perfect Overclock":{wd:0,conditional:true,note:"You and allies within 7m of your deployed skills gain +25% reload speed and reduces active cooldowns by 0.2 each second."},
  "Perfect Creeping Death":{wd:10,conditional:true,note:"When you apply a status effect it also applies to all enemies within 8m. Cooldown 15s."},
  "Perfect Composure":{wd:15,conditional:true,note:"While in cover, increases total weapon damage by 15%."},
  "Perfect Hardened":{conditional:true,note:"Increases armor by 10%."},
  "Perfect Clutch":{chc:5,conditional:true,note:"Critical hits restore 2% armor."},
  "Perfect Patience":{conditional:true,note:"After being in cover for 3s, repair 3% armor per second."},
  "Perfect Concussion":{hsd:15,conditional:true,note:"Headshots grant +10% headshot damage for 10s, stacking up to 5 times."},
  "Perfect Shock & Awe":{conditional:true,note:"Applying a status effect to an enemy increases total skill damage and repair by 20% for 20s."},
  "Perfect Wicked":{wd:18,conditional:true,note:"+18% weapon damage for 20s after applying a status effect."},
  "Perfect Bloodsucker":{conditional:true,note:"Killing an enemy adds +10% bonus armor for 10s. Max 10 stacks."},
  "Perfect Unstoppable Force":{wd:25,conditional:true,note:"Killing an enemy increases weapon damage by 5% for 15s. Stacks up to 5."},
  "Perfect Versatile":{wd:35,conditional:true,note:"Swapping weapons amplifies weapon damage based on weapon type for 10s."},
  "Perfect Perfect Hardened":{conditional:true,note:"Increases armor by 15%."},
  "Perfect Perfect Obliterate":{wd:20,conditional:true,note:"Critical hits increase weapon damage by 1% for 5s, stacking up to 25%. Stacks refresh on crit."},
  "Perfect Perfect Intimidate":{wd:40,conditional:true,note:"+40% weapon damage to enemies within 10m while you have bonus armor."},
  "Perfect Perfect Spark":{wd:20,conditional:true,note:"Applying a status effect grants +20% weapon damage for 15s."},
  "Perfect Perfect Glass Cannon":{wd:30,conditional:true,note:"All damage amplified by 30%. All damage taken amplified by 50%."},
  "Perfect Perfectly Unbreakable":{conditional:true,note:"When armor is depleted, repair 115% of total armor. Cooldown 60s."},
  "Perfect Perfect Gunslinger":{wd:28,conditional:true,note:"Weapon swapping increases total weapon damage by 28% for 5s. This buff is lost for 5s if you weapon swap while it is active."},
  "Perfect Perfect Vanguard":{wd:0,conditional:true,note:"Deploying a shield makes it invulnerable for 5s and grants 60% of your armor as bonus armor to all allies for 20s."},
  "Perfect Perfect Spotter":{wd:20,conditional:true,note:"+20% weapon and skill damage to pulsed enemies."},
  "Perfect Perfect Overwatch":{wd:20,conditional:true,note:"While in cover, shots that hit enemies beyond 25m grant +3% weapon damage for 5s, stacking up to 15 times."},
  "Perfect Perfect Headhunter":{hsd:20,conditional:true,note:"After landing a headshot, your next weapon shot deals +150% of that weapon's damage."},
  "Perfect Perfect Trauma":{hsd:15,conditional:true,note:"Headshots apply bleed to the target. Bleeding enemies take +20% weapon damage from you."},
  "Perfect Perfect Kinetic Momentum":{conditional:true,note:"Each active skill generates stacks granting +1.5% skill damage and +3% skill repair, up to 15 stacks."},
  "Perfect Perfect Companion":{wd:15,conditional:true,note:"While a skill is active, gain +15% weapon damage. While no skill is active, gain +15% skill damage."},
  "Perfect Perfectly Explosive Delivery":{wd:35,conditional:true,note:"Throwing a grenade grants +35% weapon damage for 10s."},
  "Perfect Perfectly Mad Bomber":{wd:0,conditional:true,note:"+50% Grenade Damage. +50% Grenade Radius."},
  "Perfect Perfect Braced":{wd:20,conditional:true,note:"While in cover, gain +20% weapon damage and +20% weapon handling."},
  "Perfect Perfect Focus":{wd:30,conditional:true,note:"Every 0.5s you remain stationary, gain +5% weapon damage, up to +50%."},
  "Perfect Entrench":{wd:0,conditional:true,note:"If you are below 30% armor, headshots from cover repair 20% of your armor. Cooldown: 2s."},
  "Perfect Protected Reload":{wd:0,conditional:true,note:"Grants +20% bonus armor while reloading. Grants 0-18% of your armor as bonus armor to allies when they reload."},
  "Perfect Companion":{wd:15,conditional:true,note:"While you are within 5m of an ally or skill, total weapon damage is increased by 15%."},
  "Perfect Perfect Entrench":{conditional:true,note:"Headshots while in cover grant +10% armor for 5s."},
  "Perfect Perfectly Skilled":{wd:25,conditional:true,note:"Activating a skill grants +25% weapon damage for 15s."},
  "Perfect Challenger":{wd:30,conditional:true,note:"Exotic: Killing an enemy within 10m grants +5% weapon damage for 10s, stacking up to 10 times."},
  "Perfect Bond":{wd:10,conditional:true,note:"Exotic: Gain +5% weapon damage for each active skill. Gain +5% skill damage for each active weapon."},
  "Perfect Parabellum Rounds":{wd:0,conditional:true,note:"Ongoing Directive 4pc amplifier: Increases Hollow-Point Ammo damage from 20% to 50%. Does not apply to party members."},
  "Perfect Snowball":{wd:20,conditional:true,note:"Tipping Scales: Increase the Critical Hit Damage received per stack from 4% to 7%."},
  "Perfect Risk Management":{wd:10,conditional:true,note:"Striker's Battlegear: Increases total weapon damage gained per stack of Striker's Gamble from 0.65% to 0.9%."},
  "Perfect Hollow-Point Ammo":{wd:20,conditional:true,note:"Ongoing Directive: Enemies affected by a status effect drop Hollow-Point Ammo on death. Hollow-Point Ammo deals +20% weapon damage."},
  "Perfect Makeshift Repairs":{conditional:true,note:"Foundry Bulwark: Shooting an enemy repairs 0.5% of your armor per hit. Cooldown: 0.5s."},
  "Perfect Overcharge":{conditional:true,note:"Hard Wired: Activating a skill grants Overcharge for 15s. Cooldown: 60s."},
  "Perfect Proliferation":{conditional:true,note:"Eclipse Protocol: Status effects you apply spread to one additional enemy within 8m. Cooldown: 5s."},
  "Perfect Aces High":{wd:40,conditional:true,note:"Aces & Eights: Headshots grant a stack of +5% weapon damage (max 8). Stacks are lost when you reload."},
  "Perfect Bulwark Protocol":{wd:20,conditional:true,note:"Aegis: Deploying a shield grants +20% weapon damage to all allies within 20m for 10s."},
  "Perfect Umbra Protocol":{wd:25,conditional:true,note:"Umbra Initiative: Kills grant +5% weapon damage for 10s, stacking up to 5 times."},
  "Perfect Scales of Justice":{wd:25,conditional:true,note:"Tipping Scales: Kills with LMGs grant +5% weapon damage for 10s, stacking up to 5 times."},
  "Perfect Press the Advantage":{wd:20,conditional:true,note:"Striker's Battlegear: Increases max stacks for Striker's Gamble from 100 to 200."},
  "Perfect Stars and Stripes":{wd:10,conditional:true,note:"True Patriot: Shooting an enemy applies a debuff. Debuffed enemies take +10% weapon damage from all sources."},
  "Perfect Tactical Superiority":{wd:10,conditional:true,note:"Ongoing Directive: Hollow-Point Ammo also applies a status effect on hit."},
  "Perfect Armor Overflow":{conditional:true,note:"Foundry Bulwark: Bonus armor from Foundry set bonuses is increased by 50%."},
  "Perfect Feedback Loop":{conditional:true,note:"Hard Wired: Skill kills reduce all skill cooldowns by 20%."},
  "Perfect Symptom Aggravator":{wd:20,conditional:true,note:"Eclipse Protocol: Enemies with 3 or more status effects take +20% weapon and skill damage."},
  "Perfect Dead Man's Hand":{hsd:50,conditional:true,note:"Aces & Eights: Headshots deal +50% weapon damage when you have 8 stacks of Aces High."},
  "Perfect Shield Surge":{wd:20,conditional:true,note:"Aegis: Shield health is increased by 50%. Destroying a shield grants +20% weapon damage for 10s."},
  "Perfect Umbra Surge":{wd:25,conditional:true,note:"Umbra Initiative: Kills grant +5% weapon damage for 10s, stacking up to 5 times."},
  "Perfect Sustainability":{wd:15,conditional:true,note:"Tipping Scales: Increase the maximum number of stacks from 50 to 75."},
  "Perfect Point of no Return":{wd:10,conditional:true,note:"Breaking Point: Increase On Point bonuses timer from 10s to 15s."},
  "Perfect Overcharging":{wd:0,conditional:true,note:"Cavalier: Increases Charger max incoming damage protection to 70%."},
  "Perfect All for One":{wd:0,conditional:true,note:"Concentrated Company: Increase the amount of marks that can be placed from 4 to 8."},
  "Perfect Max BPM":{wd:0,conditional:true,note:"Heartbreaker: Max stack is now 100."},
  "Perfect Endless Hunger":{wd:20,conditional:true,note:"Hotshot: Increases the duration of Apex Predator stacks from 10s to 30s."},
  "Perfect Hivemind":{conditional:true,note:"Hunter's Fury: Decrease the Overcharge cooldown from 40s to 25s."},
  "Perfect Target Rich Environment":{chd:10,conditional:true,note:"Measured Assembly: Increases Crowd Control mark count from 3 to 5."},
  "Perfect Chain Combustion":{wd:0,conditional:true,note:"Ortiz: Exuro: Enemies set ablaze by the Ortiz Incinerator Turret Prototype ignite other enemies within 2m."},
  "Perfect Best Buds":{conditional:true,note:"Refactor: Increase the damage buff from 25% to 50%."},
  "Perfect Specialized Destruction":{wd:15,conditional:true,note:"System Corruption: Increase Aggressive Recon Signature Weapon Damage bonus from 15% to 30%."},
  "Perfect Waving the Flag":{wd:10,conditional:true,note:"True Patriot: Increases Red, White, and Blue rotation speed to 1.5 seconds."},
  "Perfect Fortissimo":{wd:20,conditional:true,note:"Virtuoso: Double the weapon damage bonus from Symphony."},
  "Perfect Point of Honor":{wd:10,conditional:true,note:"Breaking Point: Increases On Point Weapon Damage bonus from 4% to 7.2%."},
  "Perfect Safe Charging":{wd:0,conditional:true,note:"Cavalier: Charging gives 10% protection per second."},
  "Perfect One for All":{wd:10,conditional:true,note:"Concentrated Company: Increase the Weapon Damage bonus per stack from 3% to 5%."},
  "Perfect Advanced Combat Tactics":{conditional:true,note:"Future Initiative: Increases Ground Control proximity repair from 60% to 120%."},
  "Perfect Cold":{conditional:true,note:"Heartbreaker: Stacks now supply +2% bonus armor."},
  "Perfect Overwhelming Force":{wd:10,conditional:true,note:"Hotshot: Increases the radius of disorient on Apex Predator kills from 5m to 10m."},
  "Perfect Smart Cooperation":{conditional:true,note:"Hunter's Fury: Decrease the cooldown for destroying Mortars and enemy skills from 10s to 1s."},
  "Perfect Critical Measures":{chd:15,conditional:true,note:"Measured Assembly: Increases Crowd Control damage to additional marked enemies from 60% to 112%."},
  "Perfect Trauma Specialist":{wd:10,conditional:true,note:"Negotiator's Dilemma: Increases duration of bleed status effects by 50% and all bleed damage done by 100%."},
  "Perfect Heatstroke":{wd:25,conditional:true,note:"Ortiz: Exuro: +25% Weapon Damage to enemies set on fire by the Ortiz Incinerator Turret Prototype."},
  "Perfect Complete Uptime":{conditional:true,note:"Refactor: Cancelling your skills will reset their cooldown."},
  "Perfect Signature Moves":{wd:20,conditional:true,note:"System Corruption: +50% Weapon Damage for 15s after fully depleting the Signature Weapon of ammo."},
  "Perfect Accelerando":{wd:10,conditional:true,note:"Virtuoso: Decreases the number of stacks needed to proc the Symphony double buffs from 4 to 3."},
  "Perfect Perfect Vigilance":{wd:30,conditional:true,note:"Increases weapon damage by 30%. Taking damage disables this bonus for 4s."},
  "Perfect Perfect Composure":{wd:20,conditional:true,note:"While in cover, increases total weapon damage by 20%."},
  "Perfect Perfect Clutch":{chc:6,conditional:true,note:"Critical hits restore 3% armor."},
  "Perfect Perfect Concussion":{hsd:20,conditional:true,note:"Headshots grant +15% headshot damage for 10s, stacking up to 5 times."},
  "Perfect Perfectly Wicked":{wd:25,conditional:true,note:"+25% weapon damage for 20s after applying a status effect."},
  "Perfect Perfect Bloodsucker":{conditional:true,note:"Killing an enemy adds +15% bonus armor for 10s. Max 10 stacks."},
  "Perfect Perfectly Unstoppable Force":{wd:30,conditional:true,note:"Killing an enemy increases weapon damage by 8% for 15s. Stacks up to 5."},
  "Perfect Perfect Versatile":{wd:45,conditional:true,note:"Swapping weapons amplifies weapon damage based on weapon type for 10s. Bonus is 50% higher."},
  "Perfect Perfect Shock and Awe":{wd:25,conditional:true,note:"Applying a status effect grants +25% weapon damage for 10s."},
  "Perfect Perfect Creeping Death":{wd:15,conditional:true,note:"When you apply a status effect it also applies to all enemies within 12m. Cooldown 10s."},
  "Perfect Perfect Overclock":{conditional:true,note:"Activating a skill overcharges it for 10s, granting +50% skill damage and +50% skill repair."},
  "Perfect Perfect Leadership":{wd:20,conditional:true,note:"Kills grant +5% weapon damage to all allies for 10s. Stacks up to 5 times."},
  "Perfect Perfect Adrenaline Rush":{wd:20,conditional:true,note:"Sprinting for 0.5s grants +20% weapon damage for 5s."},
  "Perfect Perfect Combined Arms":{wd:25,conditional:true,note:"Damaging an enemy with a skill increases weapon damage by 25% for 10s."},
  "Perfect Perfectly Calculated":{conditional:true,note:"Skill kills grant +30% skill damage for 15s."},
  "Perfect Perfect Energize":{wd:20,conditional:true,note:"Activating a skill grants +20% weapon damage for 15s."},
  "Perfect Perfect Galvanize":{conditional:true,note:"Applying a status effect grants +30% skill damage for 15s."},
  "Perfect Perfect Tech Support":{conditional:true,note:"Repairing a skill grants +25% skill damage for 15s."},
  "Perfect Perfectly Tamper Proof":{wd:0,conditional:true,note:"Enemies that destroy your skills take 500% of the skill's remaining health as damage."},
  "Perfect Perfectly Opportunistic":{wd:25,conditional:true,note:"Applying a disrupt, blind, or confuse to an enemy grants +25% weapon damage for 10s."},
  "Perfect Fireworks Show":{wd:30,conditional:true,note:"Killing an enemy with a grenade grants +30% weapon damage for 10s."},
  "Perfect Rebalance":{wd:20,conditional:true,note:"Exotic: Gain +10% weapon damage for each equipped gear set or brand set bonus active."},
  "Perfect Combat Medic":{conditional:true,note:"Exotic: Repairing an ally also repairs 20% of your armor. Repairing yourself also repairs 20% of all allies' armor."},
  "Perfect Bewildered":{wd:40,conditional:true,note:"Applying a disorient to an enemy grants +40% weapon damage for 10s."},
  "Perfect Flurry":{conditional:true,note:"Applying a status effect grants +20% status effect damage for 10s."},
  "Perfect Toxic Delivery":{conditional:true,note:"Status effects also apply a DoT for 10s equal to 50% of concussion grenade damage, increased by status effect attributes."},
  "Perfect Pack Instinct":{chc:10,chd:10,conditional:true,note:"0-15m: +25% CHD. 15-25m: +10% CHD +10% CHC. 25m+: +25% CHC."},
  "Perfect Vicious Cycle":{wd:15,conditional:true,note:"Taking damage builds stacks (max 30), each granting 1% WD. At max stacks, purge triggers a healing cloud restoring 5% armor/s for 10s."},
  "Perfect Bleeding Edge":{wd:10,conditional:true,note:"Shooting enemies within 15m applies bleed. Repair 3-48% armor/s per bleeding enemy within 15m."},
  "Perfect Ablative Nano-Plating":{conditional:true,note:"When armor breaks (you or ally), grant 80% of your armor as bonus armor for 10s. Cooldown 45s per ally."},
  "Perfect Hoarder":{wd:0,conditional:true,note:"+3 Grenade Capacity, +50% Grenade Radius, +35% Grenade Damage, +25% per extra enemy in blast. Auto-regen grenades every 30s if below 2."},
  "Perfect Kill Confirmed":{wd:15,conditional:true,note:"Enemies drop trophies on death. Collecting grants short-term buff (scales with core count) and long-term +1% WD/SE/0.1% ArmorRegen per trophy for 300s (max 30)."},
  "Perfect One in Hand":{conditional:true,note:"Throwing a grenade refunds it and grants +1 Skill Tier for 15s. Grants Overcharge if already at Tier 6. Cooldown 60s."},
  "Perfect Resourceful":{wd:0,conditional:true,note:"Slots in with any equipped Gear Set or Brand Set to fulfill a set bonus requirement. Can unlock bonuses from multiple sets simultaneously."},
  "Perfect Transference Overclock":{conditional:true,note:"+15% Hive skill haste per skill tier. Detonating a Hive refreshes all allies skill cooldowns and grants Overcharge for 15s. Cooldown 120s per ally."},
  "Perfect Over the Top":{wd:25,conditional:true,note:"Grenade or melee hit activates Seeing Red: +25% WD +100% melee damage for 20s. Cooldown 60s (reset by melee/grenade hit)."},
  "Perfect Iron Grip":{conditional:true,note:"-50% recoil penalty when hip-firing. -50% recoil penalty when blind-firing from cover."},
  "Perfect Weakest Link":{wd:20,conditional:true,note:"Shots mark the enemy with the lowest armor in a group. Marked enemies take +20% weapon damage from all sources for 10s."},
  "Perfect Quick Draw":{hsd:20,conditional:true,note:"While pistol is holstered, gain stacking buff every 0.5s (max 100). Swapping to pistol consumes buff: first shot deals +10% damage per stack as headshot damage."},
  "Perfect Dragon's Glare":{conditional:true,note:"While in combat, applies burn to the closest enemy within 20m. Cooldown 40s."},
  "Perfect Counter":{wd:20,conditional:true,note:"Weapon swapping cycles bonuses: 1) +20% RoF +20% WD, 2) +50% Mag Size +50% Reload Speed. Each lasts 12s or until next swap. Sidearm swap does not trigger."},
  "Perfect Alternating Current":{conditional:true,note:"Generate 3% skill damage stack on one skill every second (max 10). After 10s at cap, stacks transfer to other skill. Repeats indefinitely."},
  "Perfect Defibrillator":{wd:0,conditional:true,note:"-50% stun from Shock. Shield melee deals +100% damage. With St. Elmo's: melee applies Shock with 5m radius. Cooldown 15s."},
  "Perfect Rooted":{wd:20,conditional:true,note:"While in cover, gain +20% weapon damage. Moving out of cover removes the bonus for 5s."},
  "Perfect Escape Plan":{wd:0,conditional:true,note:"Vaulting/climbing/dropping gives +10% Move Speed for 3s. Not moving for 5s gives +20% Move Speed for 5s. Status effect gives +10% Move Speed for 5s. -50% movement impairment from status effects."},
  "Perfect Slotted (Investor)":{chd:10,conditional:true,note:"Receive bonuses for each non-Core Attribute on this item: Red = +10% Crit Damage, Yellow = +5% Skill Efficiency, Blue = +1% Armor Regen. (PvP: 0.5% Armor Regen)"},
  "Perfect Augment: Quantum":{wd:0,conditional:true,note:"Provides a small chance to become temporarily immune to damage."},
  "Perfect Augment: Echo":{wd:10,conditional:true,note:"Each bullet fired has a chance to deal its damage a second time."},
  "Perfect Augment: Atomize":{conditional:true,note:"Increases grenade radius and damage."},
  "Perfect Augment: Amalgam":{conditional:true,note:"Each bullet hit has a chance to apply a random status effect."},
  "Perfect Augment: Trapper":{conditional:true,note:"Increases the duration of status effects you apply."},
  "Perfect Augment: Entropy":{conditional:true,note:"Increases your Health based on a percentage of your total Armor."},
  "Perfect Augment: Anomaly":{conditional:true,note:"Skills restore a portion of the damage they deal as healing."},
  "Perfect Augment: Paradox":{wd:5,conditional:true,note:"Provides a chance to refill part of your magazine while firing."},
  "Perfect Augment: Synesthesia":{conditional:true,note:"Bullet hits have a chance to slightly reduce skill cooldowns."},