const WEAPON_TALENTS={
  none:{name:"— нет —",bonus:null},
  optimist:{name:"Optimist",bonus:{wd:10,conditional:true,note:"Weapon damage increases by 1% for every 5% of missing ammo."}},
  measured:{name:"Measured",bonus:{wd:8,note:"Top half of mag: +15% ROF, -15% damage. Bottom half: -15% ROF, +15% damage."}},
  perpetuation:{name:"Perpetuation",bonus:{hsd:12,conditional:true,note:"Headshot kills grant +1 skill tier for 10s, up to 3."}},
  flatline:{name:"Flatline",bonus:{wd:20,conditional:true,note:"Killing an enemy with a status effect grants +20% weapon damage for 10s."}},
  strained:{name:"Strained",bonus:{chd:20,conditional:true,note:"+5% critical hit damage for every 10% of max armor depleted."}},
  spike:{name:"Spike",bonus:{hsd:15,conditional:true,note:"Headshots grant +25% skill damage for 5s."}},
  ranger:{name:"Ranger",bonus:{wd:15,conditional:true,note:"+2% weapon damage for every 5m distance to the target."}},
  close_personal:{name:"Close & Personal",bonus:{wd:25,conditional:true,note:"Kills within 7m grant +50% weapon damage for 10s."}},
  preservation:{name:"Preservation",bonus:{wd:5,note:"Kills repair 2% armor over 3s."}},
  rifleman:{name:"Rifleman",bonus:{hsd:10,conditional:true,note:"Headshots mark the target. Hitting a marked target grants +15% weapon damage for 5s."}},
  boomerang:{name:"Boomerang",bonus:{wd:12,conditional:true,note:"After reloading, the first bullet deals +100% weapon damage."}},
  pummel:{name:"Pummel",bonus:{wd:8,conditional:true,note:"3 consecutive kills grant +50% melee damage for 10s."}},
  allegro:{name:"Allegro",bonus:{wd:5,note:"+10% rate of fire."}},
  frenzy:{name:"Frenzy",bonus:{wd:20,conditional:true,note:"Reloading from empty grants +20% weapon damage and +20% rate of fire for 7s."}},
  ignited:{name:"Ignited",bonus:{wd:20,conditional:true,note:"+20% weapon damage to burning enemies."}},
  determined:{name:"Determined",bonus:{wd:8,note:"Kills reduce skill cooldowns by 10%."}},
  surgical:{name:"Surgical",bonus:{chc:10,note:"+15% critical hit chance for the first bullet in each magazine."}},
  unhinged:{name:"Unhinged",bonus:{wd:35,conditional:true,note:"+35% weapon damage, -35% weapon handling."}},
  naked:{name:"Naked",bonus:{wd:35,conditional:true,note:"+35% weapon damage when no attachments are equipped."}},
  in_sync:{name:"In Sync",bonus:{wd:20,conditional:true,note:"Hitting an enemy with a skill grants +20% weapon damage for 5s."}},
  capacitor_exotic:{name:"Capacitor (Exotic)",bonus:{wd:30,conditional:true,note:"+5% weapon damage per skill tier equipped (up to +30% at tier 6). Resets on weapon swap."}},
  eagle_bearer_exotic:{name:"Eagle Bearer (Exotic)",bonus:{wd:25,conditional:true,note:"Kills grant a stack of +1% weapon damage (up to 50). Stacks reset on reload or weapon swap."}},
  chameleon_exotic:{name:"Chameleon (Exotic)",bonus:{wd:20,chd:20,conditional:true,note:"Hitting 30 body shots grants +20% weapon damage. Hitting 30 headshots grants +20% crit damage. Both can be active simultaneously."}},
  agitator_exotic:{name:"Agitator (Exotic)",bonus:{wd:30,rof:25,conditional:true,note:"Perturb: While holstered, generates 50% less threat. After 10s holstered, primes the weapon. On swap-in: +25% Rate of Fire, +30% Weapon Damage, +100% threat for 20s. Swapping away "}},
  nemesis_exotic:{name:"Nemesis (Exotic)",bonus:{wd:50,conditional:true,note:"Marks a target on aim. Damage to marked target increases by 5% per 0.5s aimed (up to +50%)."}},
  pestilence_exotic:{name:"Pestilence (Exotic)",bonus:{wd:20,note:"Shots apply Plague of the Outcasts. Enemies with the plague that die spread it to nearby enemies."}},
  ouroboros_exotic:{name:"Ouroboros (Exotic)",bonus:{wd:50,conditional:true,note:"Every 10 bullets fired grants +5% weapon damage (up to +50%). Resets on reload."}},
  scorpio_exotic:{name:"Scorpio (Exotic)",bonus:{wd:20,conditional:true,note:"Shots apply Bleed, Burn, and Shock. Enemies affected by all 3 take +20% weapon damage."}},
  regicide_exotic:{name:"Regicide (Exotic)",bonus:{hsd:50,wd:20,conditional:true,note:"Headshot kills create a 5m explosion dealing 400% weapon damage and applying bleed to all nearby enemies."}},
  mosquito_song_exotic:{name:"Mosquito Song (Exotic)",bonus:{wd:25,conditional:true,note:"Hitting an enemy applies a stack (shared between players). At 5 stacks, the enemy forcefully targets the last player to apply a stack for 5s and takes +25% more damage to armor."}},
  restrained_exotic:{name:"Restrained (Exotic)",bonus:{wd:25,conditional:true,note:"+25% weapon damage for 20s after your shield is destroyed."}},
  elmos_mark_exotic:{name:"Elmo's Mark (Exotic)",bonus:{wd:20,conditional:true,note:"Shots apply Elmo's Mark. Marked enemies take +20% weapon damage from all sources."}},
  back_and_forth:{name:"Back and Forth",bonus:{wd:9,rof:10,conditional:true,note:"Swapping to this weapon grants +10% Rate of Fire and +9% Weapon Damage for 10s. Swapping from grants +5% Rate of Fire and +4.5% Weapon Damage for 10s. Two instances do not stack."}},
  perfect_back_and_forth:{name:"Perfect Back and Forth",bonus:{wd:12,rof:13,conditional:true,note:"Swapping to this weapon grants +13% Rate of Fire and +12% Weapon Damage for 10s. Swapping from grants +5% Rate of Fire and +4.5% Weapon Damage for 10s. Two instances do not stack."}},
  cover_shooter_exotic:{name:"Cover Shooter (Exotic)",bonus:{wd:20,conditional:true,note:"Shooting from cover marks the target. Marked targets take +20% weapon damage from all sources. Mark lasts 5s."}},
  bighorn_exotic:{name:"Bighorn (Exotic)",bonus:{wd:20,hsd:50,conditional:true,note:"Switching to full-auto mode grants +20% weapon damage and +20% rate of fire for 5s. Switching to semi-auto mode grants +50% headshot damage for 5s."}},
  payment_in_kind_exotic:{name:"Payment in Kind (Exotic)",bonus:{wd:50,conditional:true,note:"Kills grant a stack of +5% weapon damage (max 10). Stacks are lost when you reload or swap weapons."}},
  unnerve_exotic:{name:"Unnerve (Exotic)",bonus:{wd:20,conditional:true,note:"Shots apply Unnerve. Unnerved enemies deal -20% damage. Killing an Unnerved enemy grants +20% weapon damage for 10s."}},
  breathe_free_exotic:{name:"Breathe Free (Exotic)",bonus:{wd:50,rof:50,conditional:true,note:"Kills grant +5% rate of fire for 5s, stacking up to 10 times. At max stacks, gain +50% weapon damage for 5s."}},
  chatterbox_exotic:{name:"Chatterbox (Exotic)",bonus:{rof:20,conditional:true,note:"Kills with a full magazine grant +20% rate of fire for 10s. Reloading within 5s of a kill refills the magazine from reserves."}},
  bluescreen_exotic:{name:"Bluescreen (Exotic)",bonus:{wd:20,conditional:true,note:"Shots apply a stack of Bluescreen. At 10 stacks, the enemy is disrupted for 5s and takes +20% weapon damage for 10s."}},
  bullet_king_exotic:{name:"Bullet King (Exotic)",bonus:{wd:15,conditional:true,note:"Kills do not consume ammo from the magazine. Reloading removes this effect until the next kill."}},
  iron_lung_exotic:{name:"Iron Lung (Exotic)",bonus:{wd:45,conditional:true,note:"While aiming, shots deal +20% weapon damage. Shots that hit the same target within 1s deal an additional +5% weapon damage, stacking up to 5 times."}},
  pakhan_exotic:{name:"Pakhan (Exotic)",bonus:{wd:50,rof:20,conditional:true,note:"Kills grant +5% weapon damage for 10s, stacking up to 10 times. At max stacks, gain +20% rate of fire for 10s."}},
  transfusion_exotic:{name:"Transfusion (Exotic)",bonus:{wd:15,note:"Kills repair 5% of your armor. Headshot kills repair 10% of your armor."}},
  agonizing_bite_exotic:{name:"Agonizing Bite (Exotic)",bonus:{wd:20,chd:20,conditional:true,note:"Every 10th shot is a guaranteed critical hit and applies a random status effect. Shots that hit a status-affected enemy deal +20% weapon damage."}},
  doctor_home_exotic:{name:"Doctor Home (Exotic)",bonus:{wd:20,conditional:true,note:"Kills repair 5% of your armor. Headshot kills repair 10% of your armor and grant +20% weapon damage for 10s."}},
  merciless_exotic:{name:"Merciless (Exotic)",bonus:{wd:50,conditional:true,note:"Each shot applies a Primer. Shooting a Primed enemy with the secondary fire detonates all Primers, dealing 800% weapon damage per Primer."}},
  ruthless_exotic:{name:"Ruthless (Exotic)",bonus:{wd:50,conditional:true,note:"Each shot applies a Primer. Shooting a Primed enemy with the secondary fire detonates all Primers, dealing 800% weapon damage per Primer."}},
  geri_and_freki_exotic:{name:"Geri and Freki (Exotic)",bonus:{wd:50,conditional:true,note:"Kills grant a stack of +5% weapon damage (max 10). At max stacks, the next shot deals 500% weapon damage."}},
  ortiz_assault_interface_exotic:{name:"Ortiz Assault Interface (Exotic)",bonus:{wd:30,conditional:true,note:"Shots apply a stack of Ortiz Protocol. At 10 stacks, the next shot deals 300% weapon damage and applies a random status effect."}},
  full_stop_exotic:{name:"Full Stop (Exotic)",bonus:{hsd:50,wd:30,conditional:true,note:"Headshots apply a stack of Full Stop. At 5 stacks, the next shot deals 500% weapon damage and staggers the target."}},
  in_plain_sight_exotic:{name:"In Plain Sight (Exotic)",bonus:{wd:100,chd:30,conditional:true,note:"Kills grant Stealth for 3s. While in Stealth, the next shot deals +100% weapon damage and is a guaranteed critical hit."}},
  high_priority_target_exotic:{name:"High Priority Target (Exotic)",bonus:{wd:30,hsd:20,conditional:true,note:"Headshots mark the target for 10s. Shots against marked targets deal +20% weapon damage. Killing a marked target grants +30% weapon damage for 10s."}},
  the_trap_exotic:{name:"The Trap (Exotic)",bonus:{wd:30,conditional:true,note:"Shots apply a stack of The Trap. At 5 stacks, the target is immobilized for 5s and takes +30% weapon damage for 10s."}},
  sandman_exotic:{name:"Sandman (Exotic)",bonus:{wd:20,conditional:true,note:"Kills grant +20% weapon damage for 10s. Headshot kills extend this bonus by 5s."}},
  capitulate_exotic:{name:"Capitulate (Exotic)",bonus:{wd:25,conditional:true,note:"Shots apply a stack of Capitulate. At 10 stacks, the target is disrupted for 5s and takes +25% weapon damage for 10s."}},
  liberty_exotic:{name:"Liberty (Exotic)",bonus:{wd:50,conditional:true,note:"Kills grant +5% weapon damage for 10s, stacking up to 5 times. At max stacks, the next shot deals +50% weapon damage."}},
  whiplash_exotic:{name:"Whiplash (Exotic)",bonus:{wd:30,conditional:true,note:"Shots apply a stack of Whiplash. At 10 stacks, the next shot deals 300% weapon damage and applies bleed."}},
  oxpecker_exotic:{name:"Oxpecker (Exotic)",bonus:{wd:20,conditional:true,note:"Kills grant +10% weapon damage for 10s. Headshot kills grant +20% weapon damage for 10s."}},
  perfect_stabilize:{name:"Perfect Stabilize",bonus:{conditional:true,note:"+1% Weapon Accuracy and +1% Weapon Stability per bullet shot, up to 75%. Stopping shooting starts a 6s timer, after which bonuses reset."}},
  perfect_on_empty:{name:"Perfect On Empty",bonus:{conditional:true,note:"Reloading from empty grants 80% weapon handling for 10 seconds."}},
  perfect_killer:{name:"Perfect Killer",bonus:{chd:90,conditional:true,note:"Killing an enemy with a critical hit grants 90% critical hit damage for 10 seconds."}},
  perfectly_near_sighted:{name:"Perfectly Near Sighted",bonus:{note:"Receive 100% stability at the cost of 35% optimal range."}},
  perfect_pressure_point:{name:"Perfect Pressure Point",bonus:{wd:20,conditional:true,note:"Amplifies weapon damage by 20% to enemies under status effects. After 3 kills, applies a random status effect to the next enemy hit."}},
  perfect_frenzy:{name:"Perfect Frenzy",bonus:{wd:27,rof:27,conditional:true,note:"For every 8 bullets in the magazine capacity, gain 3% rate of fire and 3% weapon damage for 9 seconds when reloading from empty."}},
  perfect_allegro:{name:"Perfect Allegro",bonus:{rof:15,note:"+15% Rate of Fire."}},
  perfect_flatline:{name:"Perfect Flatline",bonus:{wd:20,conditional:true,note:"Amplifies weapon damage by 20% to pulsed enemies. After 3 kills, applies pulse to the next enemy hit."}},
  perfect_streamline:{name:"Perfect Streamline",bonus:{wd:47,conditional:true,note:"Increase Weapon Damage by 47% when no Skills are on cooldown."}},
  perfectly_overflowing:{name:"Perfectly Overflowing",bonus:{conditional:true,note:"Every 2 reloads from empty increases your base magazine capacity by 100%."}},
  future_perfection:{name:"Future Perfection",bonus:{conditional:true,note:"Weapon kills grant +1 skill tier for 19s. Stacks up to 4 times. Weapon kills at skill tier 6 grant overcharge for 15s. Overcharge Cooldown: 90s."}},
  perfectly_ignited:{name:"Perfectly Ignited",bonus:{wd:30,conditional:true,note:"Deal 30% weapon damage to burning enemies. After 3 kills, applies burning to the next enemy hit."}},
  perfectly_close_personal:{name:"Perfectly Close & Personal",bonus:{wd:38,conditional:true,note:"Killing a target within 7 meters grants 38% weapon damage for 10 seconds."}},
  perfect_optimist:{name:"Perfect Optimist",bonus:{wd:27,conditional:true,note:"Weapon damage is increased by 4.5% for every 10% ammo missing from the magazine."}},
  perfectly_in_sync:{name:"Perfectly In Sync",bonus:{wd:20,conditional:true,note:"Hitting an enemy grants +20% skill damage for 5s. Using a skill grants +20% weapon damage for 5s. Damage increases are doubled while both buffs are active."}},
  perfect_precision_strike:{name:"Perfect Precision Strike",bonus:{wd:35,conditional:true,note:"Killing enemies farther than 20m builds up stacks (max 2). Hitting an enemy within 20m uses all stacks to provide +35% Amplified Damage to enemies within 20m for 5s."}},
  perfect_thunder_strike:{name:"Perfect Thunder Strike",bonus:{wd:35,note:"Deals 35% extra damage to shocked targets."}},
  perfectly_strained:{name:"Perfectly Strained",bonus:{chd:80,conditional:true,note:"Gain 10% critical hit damage for every 0.5 seconds you are firing. Stacks up to 8 times."}},
  perfect_preservation:{name:"Perfect Preservation",bonus:{wd:10,conditional:true,note:"Killing an enemy repairs 15% armor over 5 seconds. Headshot kills improves the repair to 30%."}},
  perfect_immobilize:{name:"Perfect Immobilize",bonus:{wd:25,conditional:true,note:"Amplifies weapon damage by 25% to ensnared enemies. After 3 kills, applies Ensnare to the next enemy hit."}},
  perfect_outsider:{name:"Perfect Outsider",bonus:{wd:15,conditional:true,note:"After killing an enemy, gain 150% optimal range and 125% accuracy for 10 seconds."}},
  perfect_unwavering:{name:"Perfect Unwavering",bonus:{conditional:true,note:"Swapping to this weapon grants 400% weapon handling for 5 seconds. Kills refresh the buff. Swapping away disables this from all weapons for 5 seconds."}},
  perfectly_measured:{name:"Perfectly Measured",bonus:{wd:10,conditional:true,note:"The top half of the magazine has +25% rate of fire and -30% weapon damage. The bottom half has -18% rate of fire and +38% weapon damage."}},
  perfectly_vindictive:{name:"Perfectly Vindictive",bonus:{chc:21,chd:21,conditional:true,note:"Killing an enemy with a status effect applied grants all group members within 20m 21% critical hit chance and 21% critical hit damage for 20 seconds."}},
  perfectly_unhinged:{name:"Perfectly Unhinged",bonus:{wd:22,conditional:true,note:"Receive 22% weapon damage at the cost of 25% stability and 25% accuracy."}},
  perfect_sadist:{name:"Perfect Sadist",bonus:{wd:35,conditional:true,note:"Deal +35% weapon damage to bleeding enemies. After 3 kills, applies bleed to the next enemy hit."}},
  perfect_fast_hands:{name:"Perfect Fast Hands",bonus:{reload:40,conditional:true,note:"Critical hits add a stack of 5% reload speed bonus. Max stack is 40."}},
  perfectly_optimized:{name:"Perfectly Optimized",bonus:{conditional:true,note:"Increase weapon handling by 40%."}},
  perfect_overwhelm:{name:"Perfect Overwhelm",bonus:{wd:48,conditional:true,note:"Suppressing an enemy grants 12% weapon damage for 12 seconds. Max stack is 4."}},
  perfectly_steady_handed:{name:"Perfectly Steady Handed",bonus:{conditional:true,note:"Hits grant a stack of 1% accuracy and stability. At 75 stacks, consumes them to refill the magazine."}},
  perfect_soft_spot:{name:"Perfect Soft Spot",bonus:{wd:24,conditional:true,note:"Destroying a Weakpoint grants 24% Weapon Damage for 15s."}},
  perfect_rifleman:{name:"Perfect Rifleman",bonus:{wd:66,conditional:true,note:"Landing headshots adds a stack of bonus 11% weapon damage for 5 seconds. Max stack is 6. Additional headshots refresh the duration."}},
  perfect_lucky_shot:{name:"Perfect Lucky Shot",bonus:{wd:15,conditional:true,note:"Magazine capacity is increased by 30%. Missed shots from cover have a 100% chance to return to the magazine."}},
  perfect_perpetuation:{name:"Perfect Perpetuation",bonus:{wd:15,conditional:true,note:"Headshots grant 75% status effect damage and duration to the next status effect you apply. Cooldown: 16 seconds."}},
  perfect_sledgehammer:{name:"Perfect Sledgehammer",bonus:{wd:20,conditional:true,note:"Dealing damage with a grenade applies a mark on target. Targets with marks take 40% more damage to armor and -10% movement speed."}},
  perfect_spike:{name:"Perfect Spike",bonus:{conditional:true,note:"Headshots grant 25% skill damage for 15 seconds."}},
  perfect_boomerang:{name:"Perfect Boomerang",bonus:{chd:20,conditional:true,note:"Critical hits have a 75% chance to return the bullet to the magazine. If a bullet is returned, the next shot has 50% increased damage."}},
  perfectly_behind_you:{name:"Perfectly Behind You",bonus:{wd:25,conditional:true,note:"Amplifies weapon damage by +25% to enemies that are not targeting you."}},
  perfectly_naked:{name:"Perfectly Naked",bonus:{hsd:50,conditional:true,note:"Hitting an enemy with no armor grants 50% headshot damage for 8 seconds."}},
  perfect_reformation:{name:"Perfect Reformation",bonus:{conditional:true,note:"Headshots grant 80% skill repair for 15 seconds."}},
  perfect_ranger:{name:"Perfect Ranger",bonus:{wd:20,conditional:true,note:"Amplifies weapon damage by 2% for every 3 meters you are away from the target."}},
  perfect_first_blood:{name:"Perfect First Blood",bonus:{hsd:30,conditional:true,note:"If scoped, your first 2 shots fired from out of combat or after fully reloading from empty deal headshot damage to any part of the body hit. Requires 8x scope or higher."}},
  perfectly_determined:{name:"Perfectly Determined",bonus:{hsd:30,chd:20,conditional:true,note:"After killing an enemy with a headshot, the next shot on any enemy is a guaranteed critical headshot. Killing an enemy will not retrigger the talent while active."}},
  perfect_eyeless:{name:"Perfect Eyeless",bonus:{wd:35,conditional:true,note:"Deal 35% weapon damage to blinded enemies. After 3 kills, applies blind to the next enemy hit."}},
  perfect_pumped_up:{name:"Perfect Pumped Up",bonus:{wd:30,conditional:true,note:"Reloading grants 6% weapon damage for 10 seconds. Stacks up to 5 times."}},
  perfect_jazz_hands:{name:"Perfect Jazz Hands",bonus:{reload:50,conditional:true,note:"Increase reload speed by 50%."}},
  perfect_pummel:{name:"Perfect Pummel",bonus:{wd:40,conditional:true,note:"2 consecutive kills refill the magazine and grant 40% weapon damage for 10 seconds."}},
  perfect_brazen:{name:"Perfect Brazen",bonus:{wd:12,conditional:true,note:"Receive +1% Amplified Damage on the next shot for each pellet that hits the target, if at least 4 pellets hit."}},
  perfectly_extra:{name:"Perfectly Extra",bonus:{conditional:true,note:"Increased magazine size by 50%."}},
  perfect_distance:{name:"Perfect Distance",bonus:{wd:10,conditional:true,note:"Increase optimal range by 100%."}},
  perfect_salvage:{name:"Perfect Salvage",bonus:{wd:10,note:"Killing a target has a 85% chance to refill the magazine."}},
  perfect_breadbasket:{name:"Perfect Breadbasket",bonus:{hsd:70,conditional:true,note:"Landing body shots adds a stack of bonus 70% headshot damage to the next headshot for 10 seconds. Max stack is 2."}},
  perfect_finisher:{name:"Perfect Finisher",bonus:{chc:35,chd:40,conditional:true,note:"Swapping from this weapon within 10 seconds of killing an enemy grants 35% critical hit chance and 40% critical hit damage for 15 seconds."}},
  future_perfection_mmr:{name:"Future Perfection (MMR)",bonus:{conditional:true,note:"Weapon kills grant +1 skill tier for 19s. Stacks up to 3 times. Weapon kills at skill tier 6 grant overcharge for 15s. Overcharge Cooldown: 90s."}},
  hidden_rock:{name:"Hidden Rock",bonus:{wd:10,conditional:true,note:"Headshots apply confuse. Cooldown: 20s."}},
};